### ISSUE TITLE
Python problems

### ISSUE THREAD

**Issue by zeevgr2** [andrewssobral/simple_vehicle_counting#26]
Using Ubuntu 16.04
Build
1. Updated CMakeLists.txt:  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}  **-fPIC** -std=gnu++0x")
2. From build folder: cmake **-D BUILD_PYTHON_SUPPORT=ON** .. and make -j4
3. Followied README.md for python: cp -r ../python/* python/

Testing 
1. ../run_simple_vehicle_counting.sh runs OK

2. ../run_python_demo.sh 
Traceback (most recent call last):
  File "./build/python/demo.py", line 4, in <module>
    import analysis
  File "/home/zeev/PYTHON/SIMPLE-VEHICLE-COUNT/simple_vehicle_counting/build/python/analysis/__init__.py", line 6, in <module>
    import pyboostcvconverter as pbcvt
ImportError: No module named pyboostcvconverter

3. Apparently \_\_init\_\_.py was missing in pyboostconverter folder, so entered 
touch python/pyboostcvconverter/\_\_init\_\_.py (i.e. Formatting may remove 

4. ../run_python_demo.sh
PBAS()
PixelBasedAdaptiveSegmenter()
VehicleCouting()
BlobTracking()
../run_python_demo.sh: line 4:  2089 Segmentation fault      (core dumped) python ./build/python/demo.py

Any suggestions to help locate the problem?

**Comment by cygi1989** [comment]
Exactly the same here, ubuntu 16.04. 
(PBAS:32707): Gtk-CRITICAL **: IA__gtk_widget_new: assertion 'g_type_is_a (type, GTK_TYPE_WIDGET)' failed
../run_python_demo.sh: line 3: 32707 Segmentation fault      (core dumped) python ./build/python/demo.py

Not sure where this came from,  seems like it may be related to matplotlib however I have been using this lib for plotting recently and it works fine.
