### ISSUE TITLE
Error importing analysis package

### ISSUE THREAD

**Issue by soubhik-theallrounder** [andrewssobral/simple_vehicle_counting#30]
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    import analysis
  File "/home/comp-proj-22/simple_vehicle_counting/python/analysis/__init__.py", line 1, in <module>
    from _analysis import *
ModuleNotFoundError: No module named '_analysis'

**Comment by sunblade** [comment]
The same issue on python 3.6.3
